Updated verify_installation

diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -36,6 +36,18 @@ inputs:
     required: false
     default: ''
 
+  cr_kind:
+    description: |
+      Kind of custom resource for checking deploy status.
+      CR is used to check the status if status provisioner is missing
+    required: false
+
+  cr_name:
+    description: |
+      Name of custom resource for checking deploy status.
+      CR is used to check the status if status provisioner is missing
+    required: false
+
 runs:
   using: 'composite'
   steps:
@@ -48,63 +60,63 @@ runs:
       # language=bash
       run: echo "ERROR_FLAG=false" >> $GITHUB_ENV
 
-#    - name: Check service is ready
-#      shell: bash
-#      # language=bash
-#      run: |
-#        # ▶️ Check service is ready
-#        provisioner_pod="NOT_FOUND"
-#        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
-#        for pod in "${pods[@]}"; do
-#          if [[ $pod == *"provisioner"* ]]; then
-#            provisioner_pod=$pod
-#          fi
-#        done
-#        if [[ $provisioner_pod != "NOT_FOUND" ]]; then
-#          echo "provisioner_pod=$provisioner_pod"
-#          for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
-#            status=$(kubectl get pod $provisioner_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
-#            if [[ "$status" == 'Succeeded' ]]; then
-#              break
-#            fi
-#            sleep ${{inputs.timeout_for_provisioner}}
-#          done
-#          if [[ "$status" != 'Succeeded' ]]; then
-#            echo $provisioner_pod pod has not Succeeded status
-#          fi
-#          echo PROVISIONER LOGS:
-#          kubectl logs $provisioner_pod -n ${{inputs.namespace}}
-#          logs=$(kubectl logs $provisioner_pod -n ${{inputs.namespace}})
-#          if [[ $logs != *"Failed components statuses are []"* ]]; then
-#            echo "::error:: Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
-#            echo PODS:
-#            kubectl get pods -n ${{inputs.namespace}}
-#            echo "ERROR_FLAG=true" >> $GITHUB_ENV
-#          fi
-#        else
-#          for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
-#            cr_yaml=$(kubectl get ${{inputs.cr_kind}} ${{inputs.cr_name}} -n "${{inputs.namespace}}" -o yaml)
-#            condition=$(echo "$cr_yaml" | yq eval '.status.conditions[] | select(.reason == "ReconcileCycleStatus")' -o=json)
-#              if ! [[ -z "$condition" ]]; then
-#                status=$(echo "$condition" | yq eval '.status' -)
-#                if [[ "$status" == 'True' ]]; then
-#                  break
-#                fi
-#              fi
-#            sleep ${{inputs.timeout_for_provisioner}}
-#          done
-#          if [[ "$status" != 'True' ]]; then
-#             echo "::error:: Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
-#             echo "ERROR_FLAG=true" >> $GITHUB_ENV
-#          fi
-#        fi
-
-    - name: Wait pods is ready
-      run: |
-        # ▶️ Wait pods is ready
-        kubectl wait pod --all --for=condition=Ready -n=${{inputs.namespace}} --timeout 200s
+    - name: Check service is ready
       shell: bash
-      continue-on-error: true
+      # language=bash
+      run: |
+        # ▶️ Check service is ready
+        provisioner_pod="NOT_FOUND"
+        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
+        for pod in "${pods[@]}"; do
+          if [[ $pod == *"provisioner"* ]]; then
+            provisioner_pod=$pod
+          fi
+        done
+        if [[ $provisioner_pod != "NOT_FOUND" ]]; then
+          echo "provisioner_pod=$provisioner_pod"
+          for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
+            status=$(kubectl get pod $provisioner_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
+            if [[ "$status" == 'Succeeded' ]]; then
+              break
+            fi
+            sleep ${{inputs.timeout_for_provisioner}}
+          done
+          if [[ "$status" != 'Succeeded' ]]; then
+            echo $provisioner_pod pod has not Succeeded status
+          fi
+          echo PROVISIONER LOGS:
+          kubectl logs $provisioner_pod -n ${{inputs.namespace}}
+          logs=$(kubectl logs $provisioner_pod -n ${{inputs.namespace}})
+          if [[ $logs != *"Failed components statuses are []"* ]]; then
+            echo "::error:: Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
+            echo PODS:
+            kubectl get pods -n ${{inputs.namespace}}
+            echo "ERROR_FLAG=true" >> $GITHUB_ENV
+          fi
+        else
+          for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
+            cr_yaml=$(kubectl get ${{inputs.cr_kind}} ${{inputs.cr_name}} -n "${{inputs.namespace}}" -o yaml)
+            condition=$(echo "$cr_yaml" | yq eval '.status.conditions[] | select(.reason == "ReconcileCycleStatus")' -o=json)
+              if ! [[ -z "$condition" ]]; then
+                status=$(echo "$condition" | yq eval '.status' -)
+                if [[ "$status" == 'True' ]]; then
+                  break
+                fi
+              fi
+            sleep ${{inputs.timeout_for_provisioner}}
+          done
+          if [[ "$status" != 'True' ]]; then
+             echo "::error:: Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
+             echo "ERROR_FLAG=true" >> $GITHUB_ENV
+          fi
+        fi
+
+#    - name: Wait pods is ready
+#      run: |
+#        # ▶️ Wait pods is ready
+#        kubectl wait pod --all --for=condition=Ready -n=${{inputs.namespace}} --timeout 200s
+#      shell: bash
+#      continue-on-error: true
 
     - name: Get pods
       run: |
@@ -178,6 +190,23 @@ runs:
         kubectl get secrets -n ${{inputs.namespace}} -o yaml > $file_name
       shell: bash
 
+    - name: Get logs from all containers in pods
+      shell: bash
+      # language=bash
+      run: |
+        # ▶️ Get logs from all containers in pods
+        file_name=artifacts/${{inputs.namespace}}_log_from_containers.txt
+        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
+        echo "Logs from all containers in pods: " > $file_name
+        for pod in "${pods[@]}"; do
+            IFS=' ' read -ra containers <<< $(kubectl get pod "$pod" -n ${{inputs.namespace}} -o jsonpath="{.spec.containers[*].name}")
+            for container in "${containers[@]}"; do
+              echo $pod $container >> $file_name
+              kubectl logs "$pod" -n ${{inputs.namespace}} -c "$container" >> $file_name
+              echo '================================================================================' >> $file_name
+            done
+        done
+
     - name: Get status provisioner logs
       run: |
         # ▶️ Get status provisioner logs
@@ -226,25 +255,8 @@ runs:
         fi
       shell: bash
 
-    - name: Get logs from all containers in pods
-      if: always()
-      run: |
-        # ▶️ Get logs from all containers in pods
-        file_name=artifacts/${{inputs.namespace}}_log_from_containers.txt
-        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
-        echo "Logs from all containers in pods: " > $file_name
-        for pod in "${pods[@]}"; do
-            IFS=' ' read -ra containers <<< $(kubectl get pod "$pod" -n ${{inputs.namespace}} -o jsonpath="{.spec.containers[*].name}")
-            for container in "${containers[@]}"; do
-              echo $pod $container >> $file_name
-              kubectl logs "$pod" -n ${{inputs.namespace}} -c "$container" >> $file_name
-              echo '================================================================================' >> $file_name
-            done
-        done
-      shell: bash
-
     - name: Get logs from test pod
-      if: always()
+      #if: always()
       run: |
         # ▶️ Get logs from test pod
         file_name=artifacts/${{inputs.namespace}}_tests.txt
@@ -283,6 +295,8 @@ runs:
         if [[ $logs == *"| FAIL |"* ]]; then
           echo "ERROR_FLAG=true" >> $GITHUB_ENV
         fi
+        kubectl cp $test_pod:/opt/robot/output artifacts/robot-results -n ${{inputs.namespace}}
+        ls -la artifacts/robot-results
       shell: bash
 
     - name: Generate artifact name
