fix after review

diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -2,21 +2,27 @@ name: 'Verify Installation Action'
 description: 'A GitHub Action to verify Kubernetes deployments including status checks, log collection, and test validation.'
 inputs:
   namespace:
-    description: 'namespace where service is installed'
+    description: |
+      Kubernetes namespace for service installation
     required: true
+
   max_attempts:
-    description: 'maximum number of attempts to verify that pod status is successful'
+    description: |
+      Maximum verification retries
     required: true
     default: 40
+
   timeout:
-    description: 'timeout between attempts'
+    description: |
+      Delay between attempts
     required: true
     default: '10s'
-  check_tests:
-    description: 'tests are installed or not (true/false)'
-    required: true
-    default: 'false'
 
+  service_branch:
+    description: |
+      Branch in service repository
+    required: false
+    default: ''
 
 runs:
   using: 'composite'
@@ -25,16 +31,16 @@ runs:
       run: mkdir -p artifacts
       shell: bash
 
-    - name: Wait pod status is ready
+    - name: Wait pods is ready
       run: |
-        #WAIT POD STATUS IS READY
-        kubectl wait pod --all --for=condition=Ready -n=${{inputs.namespace}} --timeout 100s
+        # ▶️ Wait pods is ready
+        kubectl wait pod --all --for=condition=Ready -n=${{inputs.namespace}} --timeout 300s
       shell: bash
       continue-on-error: true
 
     - name: Get pods
       run: |
-        #GET PODS
+        # ▶️ Get pods
         kubectl get pods -n ${{inputs.namespace}}
         file_name=artifacts/${{inputs.namespace}}_get_pods.txt
         kubectl get pods -n ${{inputs.namespace}} > $file_name
@@ -42,14 +48,14 @@ runs:
 
     - name: Get events from namespace
       run: |
-        #GET EVENTS FROM NAMESPACE
+        # ▶️ Get events from namespace
         file_name=artifacts/${{inputs.namespace}}_events.txt
         kubectl events -n ${{inputs.namespace}} > $file_name
       shell: bash
 
     - name: Get yaml from pods
       run: |
-        #GET YAML FROM PODS
+        # ▶️ Get yaml from pods
         file_name=artifacts/${{inputs.namespace}}_pod_yamls.txt
         IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
         echo "Yaml files from pods: " > $file_name
@@ -61,42 +67,42 @@ runs:
 
     - name: Get status provisioner logs
       run: |
-        #GET STATUS PROVISIONER LOGS
+        # ▶️ Get status provisioner logs
         IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
         for pod in "${pods[@]}"; do
           if [[ $pod == *"provisioner"* ]]; then
             provisioner_pod=$pod
           fi
         done
-        if [[ $provisioner_pod ]]; then
-          echo "provisioner_pod=$provisioner_pod"
-          for i in {1..${{inputs.max_attempts}}}; do
-            status=$(kubectl get pod $provisioner_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
-            if [[ "$status" == 'Succeeded' ]]; then
-              break
-            fi
-            sleep ${{inputs.timeout}}
-          done
-          if [[ "$status" != 'Succeeded' ]]; then
-            echo $provisioner_pod pod has not Succeeded status
-          fi
-          echo PROVISIONER LOGS:
-          kubectl logs $provisioner_pod -n ${{inputs.namespace}}
-          logs=$(kubectl logs $provisioner_pod -n ${{inputs.namespace}})
-          if [[ $logs != *"Failed components statuses are []"* ]]; then
-            echo Not all components are in succeed status after ${{inputs.max_attempts}} attempts
-            echo PODS:
-            kubectl get pods -n ${{inputs.namespace}}
-            exit 1
-          fi
-        else
+        if ! [[ $provisioner_pod ]]; then
           echo provisioner pod is not found
+          exit 0
+        fi
+        echo "provisioner_pod=$provisioner_pod"
+        for i in {1..${{inputs.max_attempts}}}; do
+          status=$(kubectl get pod $provisioner_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
+          if [[ "$status" == 'Succeeded' ]]; then
+            break
+          fi
+          sleep ${{inputs.timeout}}
+        done
+        if [[ "$status" != 'Succeeded' ]]; then
+          echo $provisioner_pod pod has not Succeeded status
+        fi
+        echo PROVISIONER LOGS:
+        kubectl logs $provisioner_pod -n ${{inputs.namespace}}
+        logs=$(kubectl logs $provisioner_pod -n ${{inputs.namespace}})
+        if [[ $logs != *"Failed components statuses are []"* ]]; then
+          echo Not all components are in succeed status after ${{inputs.max_attempts}} attempts
+          echo PODS:
+          kubectl get pods -n ${{inputs.namespace}}
+          exit 1
         fi
       shell: bash
 
     - name: Get logs from all containers in pods
       run: |
-        #GET LOGS FROM ALL CONTAINERS IN PODS
+        # ▶️ Get logs from all containers in pods
         file_name=artifacts/${{inputs.namespace}}_log_from_containers.txt
         IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
         echo "Logs from all containers in pods: " > $file_name
@@ -105,13 +111,14 @@ runs:
             for container in "${containers[@]}"; do
               echo $pod $container >> $file_name
               kubectl logs "$pod" -n ${{inputs.namespace}} -c "$container" >> $file_name
+              echo '================================================================================' >> $file_name
             done
         done
       shell: bash
 
     - name: Get logs from test pod
       run: |
-        #GET LOGS FROM TEST POD
+        # ▶️ Get logs from test pod
         file_name=artifacts/${{inputs.namespace}}_tests.txt
         IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
         for pod in "${pods[@]}"; do
@@ -119,44 +126,48 @@ runs:
             test_pod=$pod
           fi
         done
-        if [[ $test_pod ]]; then
-          echo "test_pod=$test_pod"
-          for i in {1..${{inputs.max_attempts}}}; do
-            status=$(kubectl get pod $test_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
-            if [[ "$status" == 'Running' ]]; then
-              break
-            fi
-            sleep ${{inputs.timeout}}
-          done
-          for i in {1..${{inputs.max_attempts}}}; do
-            logs=$(kubectl logs $test_pod -n ${{inputs.namespace}})
-            if [[ $logs == *"Report: /opt/robot/output/report.html"* ]]; then
-              kubectl logs $test_pod -n ${{inputs.namespace}} > $file_name
-              break
-            fi
-            sleep ${{inputs.timeout}}
-          done
-          echo 'TEST LOGS: '
-          kubectl logs $test_pod -n ${{inputs.namespace}}
-          if [[ $logs == *"| FAIL |"* ]]; then
-            exit 1
-          fi
-        else
+        if ! [[ $test_pod ]]; then
           echo There is no test pod
+          exit 0
+        fi
+        echo "test_pod=$test_pod"
+        for i in {1..${{inputs.max_attempts}}}; do
+          status=$(kubectl get pod $test_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
+          if [[ "$status" == 'Running' ]]; then
+            break
+          fi
+          sleep ${{inputs.timeout}}
+        done
+        for i in {1..${{inputs.max_attempts}}}; do
+          logs=$(kubectl logs $test_pod -n ${{inputs.namespace}})
+          if [[ $logs == *"Report: /opt/robot/output/report.html"* ]]; then
+            kubectl logs $test_pod -n ${{inputs.namespace}} > $file_name
+            break
+          fi
+          sleep ${{inputs.timeout}}
+        done
+        echo 'TEST LOGS: '
+        kubectl logs $test_pod -n ${{inputs.namespace}}
+        if [[ $logs == *"| FAIL |"* ]]; then
+          exit 1
         fi
       shell: bash
 
-    - name: Get current time
+    - name: Generate artifact name
       if: always()
       run: |
-        #GET CURRENT TIME
-        CURRENT_TIME=$(date -u +'%Y%m%d%H%M%S')
-        echo "CURRENT_TIME=$CURRENT_TIME" >> $GITHUB_ENV
+        # ▶️ Generate artifact name
+        release_name=$(echo ${{inputs.service_branch}})
+        if [[ $release_name ]]; then
+          release_name=$(echo "_$release_name" | tr '/' '_')
+        fi
+        ARTIFACT_NAME=${{github.job}}_${{inputs.namespace}}${release_name}_artifacts_$(date -u +'%Y%m%d%H%M%S')
+        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
       shell: bash
 
     - name: Upload artifact
       if: always()
       uses: actions/upload-artifact@v4
       with:
-        name: ${{github.job}}_${{inputs.namespace}}_artifacts_${{env.CURRENT_TIME}}
+        name: ${{env.ARTIFACT_NAME}}
         path: artifacts/
