update cr check

diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -65,20 +65,30 @@ runs:
 
         for i in {1..${{inputs.service_ready_max_retries}}}; do
           echo "Attempt $i/${{inputs.service_ready_max_retries}}"
-
           echo "${{inputs.crd_list}}"
-
-          if ./qubership-test-pipelines/scripts/check_cr.sh "${{inputs.crd_list}}" "${{inputs.namespace}}" && \
-             ./qubership-test-pipelines/scripts/check_resources.sh ${{inputs.namespace}}; then
+          ./qubership-test-pipelines/scripts/check_cr.sh "${{inputs.crd_list}}" "${{inputs.namespace}}"
+          cr_exit_code=$?
+          echo cr_exit_code $cr_exit_code
+          if [ $cr_exit_code -eq 0 ]; then
+            echo "CR check successful"
+          elif [ $cr_exit_code -eq 1 ]; then
+            echo "CR check in progress"
+          elif [ $cr_exit_code -eq 1 ]; then
+            echo "CR check failed"
+          fi
+          ./qubership-test-pipelines/scripts/check_resources.sh ${{inputs.namespace}}
+          resources_exit_code=$?
+          if [ $resources_exit_code -eq 0 ]; then
             echo "All checks successful"
             exit 0
+          elif [ $resources_exit_code -eq 2 ]; then
+            echo "::error:: Resources check failed"
           fi
           echo "Checks failed, retrying in ${{inputs.service_ready_retry_interval}} seconds..."
           sleep ${{inputs.service_ready_retry_interval}}
         done
-
         echo "::error:: Service not ready after ${{inputs.service_ready_max_retries}} retries"
-        exit 1
+
 
     - name: Get pods
       shell: bash
@@ -150,6 +160,7 @@ runs:
     - name: Get Secrets
       shell: bash
       run: kubectl get secrets -n ${{inputs.namespace}}
+
     - name: Get logs from test pod
       shell: bash
       # language=bash
@@ -157,14 +168,14 @@ runs:
         # ▶️ Get logs from test pod
         chmod +x ./qubership-test-pipelines/scripts/check_tests.sh
         ls -la ./qubership-test-pipelines/scripts/check_tests.sh
-        namespace="${{ inputs.namespace }}"
+        namespace="${{inputs.namespace}}"
         if [[ "${{inputs.check_tests}}" == "true" ]]; then
           for i in $(seq 1 ${{inputs.test_completion_max_retries}}); do
             echo "Attempt $i/${{inputs.test_completion_max_retries}}"
             ./qubership-test-pipelines/scripts/check_tests.sh "$namespace"
           done
         else
-          echo "Don't check tests"
+          echo "inputs.check_tests is 'false'. Don't check tests"
         fi
 
 
