update verify action

diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -71,17 +71,29 @@ runs:
         if [[ $provisioner_pod != "NOT_FOUND" ]]; then
           echo "provisioner_pod=$provisioner_pod"
           for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
+            output=$(kubectl get pod $provisioner_pod --ignore-not-found -n ${{inputs.namespace}})
+            if [ -z "$output" ]; then
+                echo "::error::Provisioner pod $provisioner_pod no longer exists"
+                echo "ERROR_FLAG=true" >> $GITHUB_ENV
+                exit 0
+            fi
             status=$(kubectl get pod $provisioner_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
+            echo $i Status $status
             if [[ "$status" == 'Succeeded' ]]; then
-              break
+                logs=$(kubectl logs $provisioner_pod -n ${{inputs.namespace}})
+                echo $logs
+                if [[ $logs == *"Failed components statuses are []"* ]]; then
+                  echo "All components are in succeed status!"
+                  echo PROVISIONER LOGS: $logs
+                  break
+                fi
             fi
             sleep ${{inputs.timeout_for_provisioner}}
           done
           if [[ "$status" != 'Succeeded' ]]; then
-            echo $provisioner_pod pod has not Succeeded status
+            echo "::error:: $provisioner_pod pod has not Succeeded status. Current status: $status"
+            echo "ERROR_FLAG=true" >> $GITHUB_ENV
           fi
-          echo PROVISIONER LOGS:
-          kubectl logs $provisioner_pod -n ${{inputs.namespace}}
           logs=$(kubectl logs $provisioner_pod -n ${{inputs.namespace}})
           if [[ $logs != *"Failed components statuses are []"* ]]; then
             echo "::error:: Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
@@ -90,21 +102,26 @@ runs:
             echo "ERROR_FLAG=true" >> $GITHUB_ENV
           fi
         else
-          echo "provisioner_pod isn't found. Checking CR..."
+          echo "Status provisioner pod is not found. Checking CR..."
           for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
             cr_yaml=$(kubectl get ${{inputs.cr_kind}} ${{inputs.cr_name}} -n "${{inputs.namespace}}" -o yaml)
-            condition=$(echo "$cr_yaml" | yq eval '.status.conditions[] | select(.reason == "ReconcileCycleStatus")' -o=json)
-              if ! [[ -z "$condition" ]]; then
-                status=$(echo "$condition" | yq eval '.status' -)
-                echo CR status: "$status"
-                if [[ "$status" == 'True' ]]; then
-                  break
-                fi
+            echo cr_yaml $cr_yaml
+            #condition=$(echo "$cr_yaml" | yq eval '.status.conditions[] | select(.reason == "ReconcileCycleStatus")' -o=json)
+            condition=$(echo "$cr_yaml" | yq eval '.status.conditions[] | select(.reason == "ReconcileCycleSucceeded")' -o=json)
+            echo condition $condition
+            if ! [[ -z "$condition" ]]; then
+              status=$(echo "$condition" | yq eval '.status' -)
+              echo status $status
+              #if [[ "$status" == 'True' ]]; then
+              if [[ "$status" == 'true' ]]; then
+                break
               fi
+            fi
             sleep ${{inputs.timeout_for_provisioner}}
           done
           if [[ "$status" != 'True' ]]; then
              echo "::error:: Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
+             echo $condition
              echo "ERROR_FLAG=true" >> $GITHUB_ENV
           fi
         fi
@@ -192,9 +209,9 @@ runs:
         fi
         echo "test_pod=$test_pod"
         for i in {1..${{inputs.max_attempts}}}; do
-          #echo attempt $i
+          echo attempt $i
           status=$(kubectl get pod $test_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
-          #echo "$status"
+          echo "$status"
           if [[ "$status" == 'Running' ]]; then
             break
           fi
@@ -203,9 +220,7 @@ runs:
         for i in {1..${{inputs.max_attempts}}}; do
           logs=$(kubectl logs $test_pod -n ${{inputs.namespace}})
           if [[ $logs == *"Report: /opt/robot/output/report.html"* ]]; then
-            kubectl cp $test_pod:/opt/robot/output artifacts/robot-results -n ${{inputs.namespace}}
-            $logs > $file_name
-            ls -la artifacts/robot-results
+            kubectl logs $test_pod -n ${{inputs.namespace}} > $file_name
             break
           fi
           sleep ${{inputs.timeout}}
@@ -213,8 +228,11 @@ runs:
         echo 'TEST LOGS:'
         kubectl logs $test_pod -n ${{inputs.namespace}}
         if [[ $logs == *"| FAIL |"* ]]; then
+          echo "::error:: Tests failed!"
           echo "ERROR_FLAG=true" >> $GITHUB_ENV
         fi
+        kubectl cp $test_pod:/opt/robot/output artifacts/robot-results -n ${{inputs.namespace}}
+        ls -la artifacts/robot-results
 
     - name: Generate artifact name
       if: always()
@@ -242,6 +260,6 @@ runs:
       run: |
         echo "${{ env.ERROR_FLAG }}"
         if [ "${{ env.ERROR_FLAG }}" == 'true' ]; then
-          echo "Service was installed with errors!"
+          echo "::error:: Service was installed with errors!"
           exit 1
         fi
