update Check service is ready

diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -61,6 +61,31 @@ runs:
       # language=bash
       run: |
         # ▶️ Check service is ready
+        max_attempts=${{ inputs.max_attempts_for_provisioner }}
+        timeout=${{ inputs.timeout_for_provisioner }}
+        namespace=${{ inputs.namespace }}
+        cr_kind=${{ inputs.cr_kind }}
+        cr_name=${{ inputs.cr_name }}
+
+        check_cr_status() {
+#          local attempt=1
+#          while [[ $attempt -le $max_attempts ]]; do
+#            echo "Checking CR status (attempt $attempt/$max_attempts)..."
+#            condition_status=$(kubectl get $cr_kind $cr_name -n $namespace -o jsonpath='{.status.conditions[?(@.reason=="ReconcileCycleStatus")].status}')
+#            if [[ "$condition_status" == "True" ]]; then
+#              echo "CR condition status is True"
+#              return 0
+#            fi
+#            sleep $timeout
+#            ((attempt++))
+#          done
+           kubectl wait $cr_kind $cr_name \
+           --for=jsonpath='{.status.phase}'=Succeeded \
+           --timeout=300s
+          return 1
+        }
+
+
         provisioner_pod="NOT_FOUND"
         IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
         for pod in "${pods[@]}"; do
@@ -100,24 +125,30 @@ runs:
             echo "ERROR_FLAG=true" >> $GITHUB_ENV
           fi
         else
-          for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
-            echo "Status provisioner pod is not found. Checking CR..."
-            cr_yaml=$(kubectl get ${{inputs.cr_kind}} ${{inputs.cr_name}} -n "${{inputs.namespace}}" -o yaml)
-            condition=$(echo "$cr_yaml" | yq eval '.status.conditions[] | select(.reason == "ReconcileCycleStatus")' -o=json)
-              if ! [[ -z "$condition" ]]; then
-                status=$(echo "$condition" | yq eval '.status' -)
-                if [[ "$status" == 'True' ]]; then
-                  break
-                fi
-              fi
-            sleep ${{inputs.timeout_for_provisioner}}
-          done
-          if [[ "$status" != 'True' ]]; then
-             echo "::error:: Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
-             echo $condition
-             echo "ERROR_FLAG=true" >> $GITHUB_ENV
+          if ! check_cr_status; then
+            echo "::error::CustomResource failed to become Ready"
+            kubectl get ${{ inputs.cr_kind }}/${{ inputs.cr_name }} -n ${{ inputs.namespace }} -o yaml
+            exit 1
           fi
         fi
+#          for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
+#            echo "Status provisioner pod is not found. Checking CR..."
+#            cr_yaml=$(kubectl get ${{inputs.cr_kind}} ${{inputs.cr_name}} -n "${{inputs.namespace}}" -o yaml)
+#            condition=$(echo "$cr_yaml" | yq eval '.status.conditions[] | select(.reason == "ReconcileCycleStatus")' -o=json)
+#              if ! [[ -z "$condition" ]]; then
+#                status=$(echo "$condition" | yq eval '.status' -)
+#                if [[ "$status" == 'True' ]]; then
+#                  break
+#                fi
+#              fi
+#            sleep ${{inputs.timeout_for_provisioner}}
+#          done
+#          if [[ "$status" != 'True' ]]; then
+#             echo "::error:: Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
+#             echo $condition
+#             echo "ERROR_FLAG=true" >> $GITHUB_ENV
+#          fi
+#        fi
 
     - name: Get pods
       shell: bash
