refactor: verify installation action

diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -64,42 +64,62 @@ runs:
         chmod +x ./qubership-test-pipelines/scripts/check_resources.sh
 
         echo "Checking CRDs: ${{inputs.crd_list}}"
+        cr_success=false
+        resources_success=false
+
         for i in {1..${{inputs.service_ready_max_retries}}}; do
           echo "Attempt $i/${{inputs.service_ready_max_retries}}"
 
-          set +e
-          ./qubership-test-pipelines/scripts/check_cr.sh "${{inputs.crd_list}}" "${{inputs.namespace}}"
-          cr_exit_code=$?
-          set -e
+          if [ "$cr_success" = "false" ]; then
+            set +e
+            ./qubership-test-pipelines/scripts/check_cr.sh "${{inputs.crd_list}}" "${{inputs.namespace}}"
+            cr_exit_code=$?
+            set -e
 
-          case $cr_exit_code in
-            0) echo "✅ CR check successful" ;;
-            1) echo "⏳ CR check in progress" ;;
-            2)
-              echo "::error:: ❌ CR check failed"
-              echo "ERROR_FLAG=true" >> "$GITHUB_ENV"
-              break
-              ;;
-          esac
-
-          set +e
-          ./qubership-test-pipelines/scripts/check_resources.sh "${{inputs.namespace}}"
-          resources_exit_code=$?
-          set -e
-
-          if [ $resources_exit_code -eq 0 ]; then
-            echo "✅ Resources checks successful"
-            break
-          elif [ $resources_exit_code -eq 1 ]; then
-            echo "⏳ Some resources are not ready"
+            case $cr_exit_code in
+              0)
+                echo "✅ CR check successful"
+                cr_success=true ;;
+              1)
+                echo "⏳ CR check in progress" ;;
+              2)
+                echo "::error:: ❌ CR check failed"
+                echo "ERROR_FLAG=true" >> "$GITHUB_ENV"
+                break ;;
+            esac
           fi
 
-          if [ $i -eq ${{inputs.service_ready_max_retries}} ]; then
-            echo "::warning:: ⚠️ Service not fully ready after ${{inputs.service_ready_max_retries}} retries"
-            echo "ERROR_FLAG=true" >> "$GITHUB_ENV"
-          else
-            echo "Retrying in ${{inputs.service_ready_retry_interval}} seconds..."
+          if [ "$resources_success" = "false" ]; then
+            set +e
+            ./qubership-test-pipelines/scripts/check_resources.sh "${{inputs.namespace}}"
+            resources_exit_code=$?
+            set -e
+
+            if [ $resources_exit_code -eq 0 ]; then
+              echo "✅ Resources checks successful"
+              resources_success=true
+            elif [ $resources_exit_code -eq 1 ]; then
+              echo "⏳ Some resources are not ready"
+            fi
+          fi
+
+          if [ "$cr_success" = "true" ] && [ "$resources_success" = "true" ]; then
+            echo "✅ All checks completed successfully!"
+            break
+          fi
+
+          if [ $i -ne ${{inputs.service_ready_max_retries}} ]; then
+            echo -e "Retrying in ${{inputs.service_ready_retry_interval}} seconds...\n"
             sleep ${{inputs.service_ready_retry_interval}}
+          else
+            if [ "$cr_success" = "false" ]; then
+              echo "::error:: ❌ CR check not successful after ${{inputs.service_ready_max_retries}} retries"
+              echo "ERROR_FLAG=true" >> "$GITHUB_ENV"
+            fi
+            if [ "$resources_success" = "false" ]; then
+              echo "::error:: ❌ Resources not ready after ${{inputs.service_ready_max_retries}} retries"
+              echo "ERROR_FLAG=true" >> "$GITHUB_ENV"
+            fi
           fi
         done
 
@@ -252,6 +272,7 @@ runs:
       shell: bash
       # language=bash
       run: |
+        # ▶️ Check deploy status
         if [[ "${{ env.ERROR_FLAG }}" == "true" ]]; then
           echo "::error:: ❌ Service was installed with errors!"
           exit 1
