feat: Add pipeline for Kafka and Kafka-service (#51)
* Initial configs

* Disabled monitoring

* Added verify_installation_kafka

* Fixed CR name

* Added helm_deploy_kafka_service action

* Added verify_installation_kafka_service action

* Fixed service_name

* Fixed cr_name

* Test sleep

* Output CR content

* Added update

* Added Clean [LATEST] with Zookeeper

* Changed service_branch for Zoo

* Added Get SVC step

* Changed zookeeperConnect

* Added zookeeperOsProject

* Removed .idea from version control

* Add TLS job

* Disable zookeeperEnableSsl

* Enable zookeeperEnableSsl

* Add stage when Zoo without TLS

* Add s3, get cert-manager resources

* New cert-manager entities

* Added upgrade [N2_RELEASE] to [LATEST_SPRINT]

* All stages

* Enable all tests

* Added debug code for timing

* Increased timeouts to 12min

* Additional timings

* 'Get logs from test pod' fixes

* Small fix

* Remove timings

* Added .md with description

diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -100,13 +100,15 @@ runs:
             echo "ERROR_FLAG=true" >> $GITHUB_ENV
           fi
         else
+          echo "Status provisioner pod is not found. Checking CR..."
           for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
-            echo "Status provisioner pod is not found. Checking CR..."
             cr_yaml=$(kubectl get ${{inputs.cr_kind}} ${{inputs.cr_name}} -n "${{inputs.namespace}}" -o yaml)
             condition=$(echo "$cr_yaml" | yq eval '.status.conditions[] | select(.reason == "ReconcileCycleStatus")' -o=json)
               if ! [[ -z "$condition" ]]; then
                 status=$(echo "$condition" | yq eval '.status' -)
                 if [[ "$status" == 'True' ]]; then
+                  echo "CR status condition is met"
+                  echo "$condition"
                   break
                 fi
               fi
@@ -167,6 +169,32 @@ runs:
         kubectl get pv | grep ${{inputs.namespace}}
         kubectl get pv | grep ${{inputs.namespace}} > $file_name
 
+    - name: Get SVC from namespace
+      shell: bash
+      # language=bash
+      run: |
+        # ▶️ Get SVC from namespace
+        file_name=artifacts/${{inputs.namespace}}_get_svc.txt
+        kubectl get svc -n ${{inputs.namespace}}
+        kubectl get svc -n ${{inputs.namespace}} > $file_name
+
+    - name: Get secrets from namespace
+      shell: bash
+      # language=bash
+      run: |
+        # ▶️ Get secrets from namespace
+        file_name=artifacts/${{inputs.namespace}}_get_secret.txt
+        kubectl get secret -n ${{inputs.namespace}}
+        kubectl get secret -n ${{inputs.namespace}} > $file_name
+
+    - name: Get yaml from secrets
+      shell: bash
+      # language=bash
+      run: |
+        # ▶️ Get yaml from secrets
+        file_name=artifacts/${{inputs.namespace}}_get_secret_yaml.txt
+        kubectl get secret -n ${{inputs.namespace}} -o yaml > $file_name
+
     - name: Get logs from all containers in pods
       shell: bash
       # language=bash
@@ -190,10 +218,12 @@ runs:
       run: |
         # ▶️ Get logs from test pod
         file_name=artifacts/${{inputs.namespace}}_tests.txt
-        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
+        IFS=' ' read -ra pods <<< "$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')"
+        test_pod=""
         for pod in "${pods[@]}"; do
           if [[ $pod == *"tests"* ]]; then
             test_pod=$pod
+            break
           fi
         done
         if ! [[ $test_pod ]]; then
@@ -201,8 +231,8 @@ runs:
           exit 0
         fi
         echo "test_pod=$test_pod"
-        for i in {1..${{inputs.max_attempts}}}; do
-          echo attempt $i
+        for i in $(seq 1 ${{inputs.max_attempts}}); do
+          echo "Attempt status $i"
           status=$(kubectl get pod $test_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
           echo "$status"
           if [[ "$status" == 'Running' ]]; then
@@ -210,21 +240,24 @@ runs:
           fi
           sleep ${{inputs.timeout}}
         done
-        for i in {1..${{inputs.max_attempts}}}; do
+        for i in $(seq 1 ${{inputs.max_attempts}}); do
+          echo "Attempt logs $i"
           logs=$(kubectl logs $test_pod -n ${{inputs.namespace}})
-          if [[ $logs == *"Report: /opt/robot/output/report.html"* ]]; then
-            kubectl logs $test_pod -n ${{inputs.namespace}} > $file_name
+          if [[ $logs =~ Report.*html ]]; then
+            echo "$logs" > $file_name
             break
           fi
           sleep ${{inputs.timeout}}
         done
         echo 'TEST LOGS:'
-        kubectl logs $test_pod -n ${{inputs.namespace}}
+        echo "$logs"
         if [[ $logs == *"| FAIL |"* ]]; then
           echo "::error:: Tests failed!"
           echo "ERROR_FLAG=true" >> $GITHUB_ENV
         fi
-        kubectl cp $test_pod:/opt/robot/output artifacts/robot-results -n ${{inputs.namespace}}
+        if ! kubectl cp $test_pod:/opt/robot/output artifacts/robot-results -n ${{inputs.namespace}}; then
+        echo "::warning:: Failed to copy robot results"
+        fi
         ls -la artifacts/robot-results
 
     - name: Generate artifact name
