chore: correct test pod restart

diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -154,83 +154,42 @@ runs:
       shell: bash
       # language=bash
       run: |
-        if [[ "${{inputs.monitoring_tests}}" == "true" ]]; then
-          NAMESPACE=${{inputs.namespace}}
-          SERVICE_MONITORS=(
-            monitoring-kube-state-metrics
-            monitoring-etcd-service-monitor
-            monitoring-kubelet-service-monitor
-            monitoring-kube-apiserver-service-monitor
-          )
-          echo "Checking if required service monitors installed..."
-          for sm in "${SERVICE_MONITORS[@]}"; do
-            attempt=1
-            max_attempts=15
-            while [[ $attempt -le $max_attempts ]]; do
-              if kubectl get servicemonitor "$sm" -n "$NAMESPACE" >/dev/null 2>&1; then
-                echo "ServiceMonitor $sm exists."
-                break
-              else
-                sleep 5s
-                ((attempt++))
-              fi
-            done
-            if [[ $attempt -gt $max_attempts ]]; then
-              echo "Max attempts reached. ServiceMonitor $sm is not found."
-              exit 1
+        NAMESPACE=${{inputs.namespace}}
+        SERVICE_MONITORS=(
+          monitoring-kube-state-metrics
+          monitoring-etcd-service-monitor
+          monitoring-kubelet-service-monitor
+          monitoring-kube-apiserver-service-monitor
+        )
+        echo "Checking if required service monitors installed..."
+        for sm in "${SERVICE_MONITORS[@]}"; do
+          attempt=1
+          max_attempts=15
+          while [[ $attempt -le $max_attempts ]]; do
+            if kubectl get servicemonitor "$sm" -n "$NAMESPACE" >/dev/null 2>&1; then
+              echo "ServiceMonitor $sm exists."
+              break
+            else
+              sleep 5s
+              ((attempt++))
             fi
           done
-          echo "Service monitors are installed. Now restarting vmagent..."
-          VMAGENT_PODS=$(kubectl get pods -n $NAMESPACE -l app.kubernetes.io/name=vmagent -o jsonpath='{.items[*].metadata.name}')
-          for vmagent in $VMAGENT_PODS; do
-            kubectl delete pod "$vmagent" -n $NAMESPACE
-            kubectl wait --for=delete "pod/$vmagent" -n $NAMESPACE --timeout=30s
-          done
-          kubectl set env deployment/monitoring-tests -n "${{inputs.namespace}}" TIMEOUT-BEFORE-START="20"
-          echo "Waiting for test pod restart..."
-          kubectl delete pod $OLD_TEST_POD  -n "${{inputs.namespace}}"
-          kubectl wait --for=delete pod/$OLD_TEST_POD -n "${{inputs.namespace}}" --timeout=120s && echo "Test pod restarted."  
-        fi
-        # ▶️ Set TIMEOUT-BEFORE-START and restart tests pod
-        if [[ "${{inputs.monitoring_tests}}" == "true" ]]; then
-          OLD_TEST_POD=$(kubectl get pods -n "${{inputs.namespace}}" -l name=monitoring-tests -o jsonpath='{.items[*].metadata.name}')
-          echo "Patching tests deployment to set TIMEOUT-BEFORE-START to 20 seconds and restart pod"
-          NAMESPACE=${{inputs.namespace}}
-          SERVICE_MONITORS=(
-            monitoring-kube-state-metrics
-            monitoring-etcd-service-monitor
-            monitoring-kubelet-service-monitor
-            monitoring-kube-apiserver-service-monitor
-          )
-          echo "Checking if required service monitors installed..."
-          for sm in "${SERVICE_MONITORS[@]}"; do
-            attempt=1
-            max_attempts=15
-            while [[ $attempt -le $max_attempts ]]; do
-              if kubectl get servicemonitor "$sm" -n "$NAMESPACE" >/dev/null 2>&1; then
-                echo "ServiceMonitor $sm exists."
-                break
-              else
-                sleep 5s
-                ((attempt++))
-              fi
-            done
-            if [[ $attempt -gt $max_attempts ]]; then
-              echo "Max attempts reached. ServiceMonitor $sm is not found."
-              exit 1
-            fi
-          done
-          echo "Service monitors are installed. Now restarting vmagent..."
-          VMAGENT_PODS=$(kubectl get pods -n $NAMESPACE -l app.kubernetes.io/name=vmagent -o jsonpath='{.items[*].metadata.name}')
-          for vmagent in $VMAGENT_PODS; do
-            kubectl delete pod "$vmagent" -n $NAMESPACE
-            kubectl wait --for=delete "pod/$vmagent" -n $NAMESPACE --timeout=30s
-          done
-          TEST_POD=$(kubectl get pods -n "${{inputs.namespace}}" -l name=monitoring-tests -o jsonpath='{.items[*].metadata.name}')
-          echo "Waiting for test pod restart..."
-          kubectl delete pod $TEST_POD  -n "${{inputs.namespace}}"
-          kubectl wait --for=delete pod/$OLD_TEST_POD -n "${{inputs.namespace}}" --timeout=120s && echo "Test pod restarted."  
-        fi
+          if [[ $attempt -gt $max_attempts ]]; then
+            echo "Max attempts reached. ServiceMonitor $sm is not found."
+            exit 1
+          fi
+        done
+        echo "Service monitors are installed. Now restarting vmagent..."
+        VMAGENT_PODS=$(kubectl get pods -n $NAMESPACE -l app.kubernetes.io/name=vmagent -o jsonpath='{.items[*].metadata.name}')
+        for vmagent in $VMAGENT_PODS; do
+          kubectl delete pod "$vmagent" -n $NAMESPACE
+          kubectl wait --for=delete "pod/$vmagent" -n $NAMESPACE --timeout=30s
+        done
+        TEST_POD=$(kubectl get pods -n "${{inputs.namespace}}" -l name=monitoring-tests -o jsonpath='{.items[*].metadata.name}')
+        echo "Waiting for test pod restart..."
+        kubectl delete pod $TEST_POD  -n "${{inputs.namespace}}"
+        kubectl wait --for=delete pod/$TEST_POD -n "${{inputs.namespace}}" --timeout=120s && echo "Test pod restarted."
+
     - name: Get logs from test pod
       if: ${{ inputs.check_tests == 'true' }}
       shell: bash
