refactor: verify installation action

diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -43,7 +43,7 @@ inputs:
     type: boolean
 
 runs:
-  using: 'composite'
+  using: "composite"
   steps:
     - name: Create folder for artifacts
       shell: bash
@@ -63,60 +63,68 @@ runs:
         chmod +x ./qubership-test-pipelines/scripts/check_cr.sh
         chmod +x ./qubership-test-pipelines/scripts/check_resources.sh
 
+        echo "📋 Checking CRDs: ${{inputs.crd_list}}"
         for i in {1..${{inputs.service_ready_max_retries}}}; do
+          echo "📋 Attempt $i/${{inputs.service_ready_max_retries}}"
 
-          echo "Attempt $i/${{inputs.service_ready_max_retries}}"
-          echo "${{inputs.crd_list}}"
-          #./qubership-test-pipelines/scripts/check_cr.sh "${{inputs.crd_list}}" "${{inputs.namespace}}" >/dev/null 2>&1
           set +e
           ./qubership-test-pipelines/scripts/check_cr.sh "${{inputs.crd_list}}" "${{inputs.namespace}}"
           cr_exit_code=$?
           set -e
-          echo cr_exit_code $cr_exit_code
-          if [ $cr_exit_code -eq 0 ]; then
-            echo "CR check successful"
-          elif [ $cr_exit_code -eq 1 ]; then
-            echo "CR check in progress"
-          elif [ $cr_exit_code -eq 2 ]; then
-            echo "CR check failed"
-          fi
+
+          echo "cr_exit_code: $cr_exit_code"
+          case $cr_exit_code in
+            0) echo "✅ CR check successful" ;;
+            1) echo "⏳ CR check in progress" ;;
+            2)
+              echo "::error:: ❌ CR check failed"
+              echo "ERROR_FLAG=true" >> "$GITHUB_ENV"
+              break
+              ;;
+          esac
+
           set +e
           ./qubership-test-pipelines/scripts/check_resources.sh "${{inputs.namespace}}"
           resources_exit_code=$?
           set -e
-          echo "resources_exit_code $resources_exit_code"
+
+          echo "resources_exit_code: $resources_exit_code"
           if [ $resources_exit_code -eq 0 ]; then
-            echo "Resources checks successful"
-            exit 0
-          elif [ $resources_exit_code -eq 2 ]; then
-            echo "Some resources are not ready"
+            echo "✅ Resources checks successful"
+            break
+          elif [ $resources_exit_code -eq 1 ]; then
+            echo "⏳ Some resources are not ready"
           fi
-          echo "Checks failed, retrying in ${{inputs.service_ready_retry_interval}} seconds..."
-          sleep ${{inputs.service_ready_retry_interval}}
+
+          if [ $i -eq ${{inputs.service_ready_max_retries}} ]; then
+            echo "::warning:: ⚠️ Service not fully ready after ${{inputs.service_ready_max_retries}} retries"
+            echo "ERROR_FLAG=true" >> "$GITHUB_ENV"
+          else
+            echo "Retrying in ${{inputs.service_ready_retry_interval}} seconds..."
+            sleep ${{inputs.service_ready_retry_interval}}
+          fi
         done
-        echo "::error:: Service not ready after ${{inputs.service_ready_max_retries}} retries"
-        exit 0
 
     - name: Get pods
       shell: bash
       # language=bash
       run: |
         # ▶️ Get pods
-        file_name=artifacts/${{inputs.namespace}}_get_pods.txt
-        kubectl get pods -n ${{inputs.namespace}}
-        kubectl get pods -n ${{inputs.namespace}} > $file_name
+        file_name="artifacts/${{inputs.namespace}}_get_pods.txt"
+        kubectl get pods -n "${{inputs.namespace}}"
+        kubectl get pods -n "${{inputs.namespace}}" > "$file_name"
 
     - name: Get yaml from pods
       shell: bash
       # language=bash
       run: |
         # ▶️ Get yaml from pods
-        file_name=artifacts/${{inputs.namespace}}_get_pods_yaml.txt
-        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
-        echo "Yaml files from pods: " > $file_name
+        file_name="artifacts/${{inputs.namespace}}_get_pods_yaml.txt"
+        IFS=" " read -ra pods <<< "$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n "${{inputs.namespace}}" | tr "\n" " ")"
+        echo "Yaml files from pods:" > "$file_name"
         for pod in "${pods[@]}"; do
-            echo $pod >> $file_name
-            kubectl get pod "$pod" -n ${{inputs.namespace}} -o yaml >> $file_name
+            echo "$pod" >> "$file_name"
+            kubectl get pod "$pod" -n "${{inputs.namespace}}" -o yaml >> "$file_name"
         done
 
     - name: Get events from namespace
@@ -124,30 +132,30 @@ runs:
       # language=bash
       run: |
         # ▶️ Get events from namespace
-        file_name=artifacts/${{inputs.namespace}}_get_events.txt
-        kubectl events -n ${{inputs.namespace}} > $file_name
+        file_name="artifacts/${{inputs.namespace}}_get_events.txt"
+        kubectl events -n "${{inputs.namespace}}" > "$file_name"
 
     - name: Get yaml from PVC
       shell: bash
       # language=bash
       run: |
         # ▶️ Get yaml from PVC
-        file_name=artifacts/${{inputs.namespace}}_get_pvc_yaml.txt
-        kubectl get pvc -n ${{inputs.namespace}}
-        kubectl get pvc -n ${{inputs.namespace}} -o yaml > $file_name
+        file_name="artifacts/${{inputs.namespace}}_get_pvc_yaml.txt"
+        kubectl get pvc -n "${{inputs.namespace}}"
+        kubectl get pvc -n "${{inputs.namespace}}" -o yaml > "$file_name"
 
     - name: Get PV from namespace
       shell: bash
       # language=bash
       run: |
         # ▶️ Get PV from namespace
-        file_name=artifacts/${{inputs.namespace}}_get_pv.txt
-        if kubectl get pv 2>/dev/null | grep ${{inputs.namespace}}; then
-          kubectl get pv | grep ${{inputs.namespace}} > $file_name
-          echo "PV found and saved to $file_name"
+        file_name="artifacts/${{inputs.namespace}}_get_pv.txt"
+        if kubectl get pv 2>/dev/null | grep -q "${{inputs.namespace}}"; then
+          kubectl get pv | grep "${{inputs.namespace}}" > "$file_name"
+          echo "✅ PV found and saved to $file_name"
         else
-          echo "No PV found for namespace ${{inputs.namespace}}" > $file_name
-          echo "No PV found for namespace ${{inputs.namespace}}"
+          echo "No PV found for namespace ${{inputs.namespace}}" > "$file_name"
+          echo "ℹ️ No PV found for namespace ${{inputs.namespace}}"
         fi
 
     - name: Get logs from all containers in pods
@@ -155,23 +163,27 @@ runs:
       # language=bash
       run: |
         # ▶️ Get logs from all containers in pods
-        file_name=artifacts/${{inputs.namespace}}_log_from_containers.txt
-        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
-        echo "Logs from all containers in pods: " > $file_name
+        file_name="artifacts/${{inputs.namespace}}_log_from_containers.txt"
+        IFS=" " read -ra pods <<< "$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n "${{inputs.namespace}}" | tr "\n" " ")"
+        echo "Logs from all containers in pods:" > "$file_name"
         for pod in "${pods[@]}"; do
-            IFS=' ' read -ra containers <<< $(kubectl get pod "$pod" -n ${{inputs.namespace}} -o jsonpath="{.spec.containers[*].name}")
+            IFS=" " read -ra containers <<< "$(kubectl get pod "$pod" -n "${{inputs.namespace}}" -o jsonpath="{.spec.containers[*].name}")"
             for container in "${containers[@]}"; do
-              echo $pod $container >> $file_name
-              kubectl logs "$pod" -n ${{inputs.namespace}} -c "$container" >> $file_name
-              echo '================================================================================' >> $file_name
+              echo "$pod $container" >> "$file_name"
+              kubectl logs "$pod" -n "${{inputs.namespace}}" -c "$container" >> "$file_name"
+              echo "================================================================================" >> "$file_name"
             done
         done
+
     - name: Get All
       shell: bash
-      run: kubectl get all -n ${{inputs.namespace}}
+      # language=bash
+      run: kubectl get all -n "${{inputs.namespace}}"
+
     - name: Get Secrets
       shell: bash
-      run: kubectl get secrets -n ${{inputs.namespace}}
+      # language=bash
+      run: kubectl get secrets -n "${{inputs.namespace}}"
 
     - name: Get logs from test pod
       shell: bash
@@ -180,18 +192,43 @@ runs:
         # ▶️ Get logs from test pod
         chmod +x ./qubership-test-pipelines/scripts/check_tests.sh
         ls -la ./qubership-test-pipelines/scripts/check_tests.sh
-        namespace="${{inputs.namespace}}"
+
         if [[ "${{inputs.check_tests}}" == "true" ]]; then
           for i in $(seq 1 ${{inputs.test_completion_max_retries}}); do
-            echo "Attempt $i/${{inputs.test_completion_max_retries}}"
-            ./qubership-test-pipelines/scripts/check_tests.sh "$namespace"
+            echo "Test check attempt $i/${{inputs.test_completion_max_retries}}"
+            set +e
+            ./qubership-test-pipelines/scripts/check_tests.sh "${{inputs.namespace}}"
+            tests_exit_code=$?
+            set -e
+
+            case $tests_exit_code in
+              0)
+                echo "✅ Tests passed successfully"
+                break
+                ;;
+              1)
+                echo "⏳ Tests still in progress"
+                ;;
+              2)
+                echo "::error:: ❌ Tests failed"
+                echo "ERROR_FLAG=true" >> "$GITHUB_ENV"
+                break
+                ;;
+            esac
+
+            if [ $i -eq ${{inputs.test_completion_max_retries}} ]; then
+              echo "::warning:: ⚠️ Tests not completed after ${{inputs.test_completion_max_retries}} retries"
+              echo "ERROR_FLAG=true" >> "$GITHUB_ENV"
+            else
+              sleep ${{inputs.service_ready_retry_interval}}
+            fi
           done
         elif [[ "${{inputs.check_tests}}" == "false" ]]; then
-          echo "inputs.check_tests is 'false'. Don't check tests"
+          echo "ℹ️ Test checking disabled"
         else
-          echo "Incorrect inputs.check_tests value: '${{inputs.check_tests}}'"
+          echo "::error:: ❌ Incorrect inputs.check_tests value: '${{inputs.check_tests}}'"
+          echo "ERROR_FLAG=true" >> "$GITHUB_ENV"
         fi
-
 
     - name: Generate artifact name
       if: always()
@@ -199,26 +236,27 @@ runs:
       # language=bash
       run: |
         # ▶️ Generate artifact name
-        release_name=$(echo ${{inputs.service_branch}})
-        if [[ $release_name ]]; then
-          release_name=$(echo "_$release_name" | tr '/' '_')
+        release_name="${{inputs.service_branch}}"
+        if [[ -n "$release_name" ]]; then
+          release_name="_${release_name//\//_}"
         fi
-        ARTIFACT_NAME=${{github.job}}_${{inputs.namespace}}${release_name}_artifacts_$(date -u +'%Y%m%d%H%M%S')
-        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
+        ARTIFACT_NAME="${{github.job}}_${{inputs.namespace}}${release_name}_artifacts_$(date -u +"%Y%m%d%H%M%S")"
+        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> "$GITHUB_ENV"
 
     - name: Upload artifact
       if: always()
       uses: actions/upload-artifact@v4
       with:
-        name: ${{env.ARTIFACT_NAME}}
+        name: "${{env.ARTIFACT_NAME}}"
         path: artifacts/
 
     - name: Check job status
       shell: bash
       # language=bash
       run: |
-        echo "${{ env.ERROR_FLAG }}"
-        if [ "${{ env.ERROR_FLAG }}" == 'true' ]; then
-          echo "::error:: Service was installed with errors!"
+        if [[ "${{ env.ERROR_FLAG }}" == "true" ]]; then
+          echo "::error:: ❌ Service was installed with errors!"
           exit 1
+        else
+          echo "✅ Service installation completed successfully"
         fi
