rename timeout variables

diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -6,24 +6,24 @@ inputs:
       Kubernetes namespace for service installation
     required: true
 
-  max_attempts:
+  service_ready_max_retries:
+    description: |
+      Maximum retries for provisioner pod or custom resource to be completed
+    required: true
+
+  service_ready_retry_interval:
+    description: |
+      Delay between provisioner pod / CR check attempts (in seconds)
+    required: true
+
+  test_completion_max_retries:
     description: |
       Maximum verification retries for test pod to be completed
     required: true
 
-  timeout:
+  test_completion_retry_interval:
     description: |
       Delay between test pod check attempts
-    required: true
-
-  max_attempts_for_provisioner:
-    description: |
-      Maximum retries for provisioner pod to be completed
-    required: true
-
-  timeout_for_provisioner:
-    description: |
-      Delay between provisioner pod check attempts
     required: true
 
   service_branch:
@@ -61,46 +61,13 @@ runs:
       # language=bash
       run: |
         # ▶️ Check service is ready
-        max_attempts=${{ inputs.max_attempts_for_provisioner }}
-        timeout=${{ inputs.timeout_for_provisioner }}
-        namespace=${{ inputs.namespace }}
-        cr_kind=${{ inputs.cr_kind }}
-        cr_name=${{ inputs.cr_name }}
-
-        check_cr_status() {
-#          local attempt=1
-#          while [[ $attempt -le $max_attempts ]]; do
-#            echo "Checking CR status (attempt $attempt/$max_attempts)..."
-#            condition_status=$(kubectl get $cr_kind $cr_name -n $namespace -o jsonpath='{.status.conditions[?(@.reason=="ReconcileCycleStatus")].status}')
-#            if [[ "$condition_status" == "True" ]]; then
-#              echo "CR condition status is True"
-#              return 0
-#            fi
-#            sleep $timeout
-#            ((attempt++))
-#          done
-           kubectl wait $cr_kind $cr_name \
-           --for=jsonpath='{.status.phase}'=Succeeded \
-           --timeout=300s
-          return 1
-        }
-
-
-        provisioner_pod="NOT_FOUND"
-        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
-        for pod in "${pods[@]}"; do
-          if [[ $pod == *"provisioner"* ]]; then
-            provisioner_pod=$pod
-          fi
-        done
-        if [[ $provisioner_pod != "NOT_FOUND" ]]; then
+        check_provisioner_pod() {
           echo "provisioner_pod=$provisioner_pod"
-          for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
+          for i in {1..${{inputs.service_ready_max_retries}}}; do
             output=$(kubectl get pod $provisioner_pod --ignore-not-found -n ${{inputs.namespace}})
             if [ -z "$output" ]; then
                 echo "::error::Provisioner pod $provisioner_pod no longer exists"
-                echo "ERROR_FLAG=true" >> $GITHUB_ENV
-                exit 0
+                return 1
             fi
             status=$(kubectl get pod $provisioner_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
             if [[ "$status" == 'Succeeded' ]]; then
@@ -111,44 +78,64 @@ runs:
                   break
                 fi
             fi
-            sleep ${{inputs.timeout_for_provisioner}}
+            sleep ${{inputs.service_ready_retry_interval}}
           done
           if [[ "$status" != 'Succeeded' ]]; then
             echo "::error:: $provisioner_pod pod has not Succeeded status. Current status: $status"
-            echo "ERROR_FLAG=true" >> $GITHUB_ENV
+            return 1
           fi
           logs=$(kubectl logs $provisioner_pod -n ${{inputs.namespace}})
           if [[ $logs != *"Failed components statuses are []"* ]]; then
-            echo "::error:: Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
+            echo "::error:: Not all components are in succeed status after ${{inputs.service_ready_max_retries}} attempts"
             echo PODS:
             kubectl get pods -n ${{inputs.namespace}}
-            echo "ERROR_FLAG=true" >> $GITHUB_ENV
+            return 1
+          fi
+        }
+
+        check_cr_status() {
+          for i in {1..${{inputs.service_ready_max_retries}}}; do
+            #condition_status=$(kubectl get ${{inputs.cr_kind}} ${{inputs.cr_name}} -n ${{inputs.namespace}} -o jsonpath='{.status.conditions[?(@.reason=="ReconcileCycleStatus")].status}')
+            cr_yaml=$(kubectl get ${{inputs.cr_kind}} ${{inputs.cr_name}} -n "${{inputs.namespace}}" -o yaml)
+            condition=$(echo "$cr_yaml" | yq eval '.status.conditions[] | select(.reason == "ReconcileCycleStatus")' -o=yaml)
+            echo  $condition
+            if ! [[ -z "$condition" ]]; then
+              status=$(echo "$condition" | yq eval '.status' -)
+              if [[ "$status" == 'True' ]]; then
+                echo "CR ${{inputs.cr_kind}} ${{inputs.cr_name}} has successful status"
+                #return 0
+              fi
+            fi
+            sleep ${{inputs.service_ready_retry_interval}}
+          done
+        }
+
+        provisioner_pod="NOT_FOUND"
+        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
+        for pod in "${pods[@]}"; do
+          if [[ $pod == *"provisioner"* ]]; then
+            provisioner_pod=$pod
+          fi
+        done
+
+        check_result=1
+
+        if [[ $provisioner_pod != "NOT_FOUND" ]]; then
+          if ! check_provisioner_pod; then
+            check_result=0
           fi
         else
+          echo "Status provisioner pod is not found. Checking CR..."
           if ! check_cr_status; then
-            echo "::error::CustomResource failed to become Ready"
-            kubectl get ${{ inputs.cr_kind }}/${{ inputs.cr_name }} -n ${{ inputs.namespace }} -o yaml
-            exit 1
+            check_result=0
           fi
         fi
-#          for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
-#            echo "Status provisioner pod is not found. Checking CR..."
-#            cr_yaml=$(kubectl get ${{inputs.cr_kind}} ${{inputs.cr_name}} -n "${{inputs.namespace}}" -o yaml)
-#            condition=$(echo "$cr_yaml" | yq eval '.status.conditions[] | select(.reason == "ReconcileCycleStatus")' -o=json)
-#              if ! [[ -z "$condition" ]]; then
-#                status=$(echo "$condition" | yq eval '.status' -)
-#                if [[ "$status" == 'True' ]]; then
-#                  break
-#                fi
-#              fi
-#            sleep ${{inputs.timeout_for_provisioner}}
-#          done
-#          if [[ "$status" != 'True' ]]; then
-#             echo "::error:: Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
-#             echo $condition
-#             echo "ERROR_FLAG=true" >> $GITHUB_ENV
-#          fi
-#        fi
+
+        if [[ $check_result -eq 0 ]]; then
+          echo "::error:: Not all components are in succeed status after ${{inputs.service_ready_max_retries}} attempts"
+          echo "$condition"
+          echo "ERROR_FLAG=true" >> $GITHUB_ENV
+        fi
 
     - name: Get pods
       shell: bash
@@ -232,22 +219,22 @@ runs:
           exit 0
         fi
         echo "test_pod=$test_pod"
-        for i in {1..${{inputs.max_attempts}}}; do
+        for i in {1..${{inputs.test_completion_max_retries}}}; do
           echo attempt $i
           status=$(kubectl get pod $test_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
           echo "$status"
           if [[ "$status" == 'Running' ]]; then
             break
           fi
-          sleep ${{inputs.timeout}}
+          sleep ${{inputs.test_completion_retry_interval}}
         done
-        for i in {1..${{inputs.max_attempts}}}; do
+        for i in {1..${{inputs.test_completion_max_retries}}}; do
           logs=$(kubectl logs $test_pod -n ${{inputs.namespace}})
           if [[ $logs == *"Report: /opt/robot/output/report.html"* ]]; then
             kubectl logs $test_pod -n ${{inputs.namespace}} > $file_name
             break
           fi
-          sleep ${{inputs.timeout}}
+          sleep ${{inputs.test_completion_retry_interval}}
         done
         echo 'TEST LOGS:'
         kubectl logs $test_pod -n ${{inputs.namespace}}
