update actions

diff --git a/actions/shared/check_results/action.yml b/actions/shared/check_results/action.yml
--- a/actions/shared/check_results/action.yml
+++ b/actions/shared/check_results/action.yml
@@ -12,6 +12,11 @@ inputs:
     description: 'timeout between attempts'
     required: true
     default: '10s'
+  check_tests:
+    description: 'tests are installed or not (true/false)'
+    required: true
+    default: 'false'
+
 
 runs:
   using: 'composite'
@@ -20,13 +25,27 @@ runs:
       run: mkdir -p artifacts
       shell: bash
 
+#    - name: Wait pod status is ready
+#      run: |
+#        #WAIT POD STATUS IS READY
+#        kubectl wait pod --all --for=condition=Ready -n=${{inputs.namespace}} --timeout 300s
+#      shell: bash
+
     - name: Get pods
-      run: kubectl get pods -n ${{inputs.namespace}}
+      run: |
+        #GET PODS
+        kubectl get pods -n ${{inputs.namespace}}
+        file_name=artifacts/${{inputs.namespace}}_get_pods.txt
+        kubectl get pods -n ${{inputs.namespace}} > $file_name
+      shell: bash
+
+    - name: Get deployments
+      run: kubectl get deployments -n ${{inputs.namespace}}
       shell: bash
 
     - name: Get status provisioner logs
       run: |
-        echo Get status provisioner logs
+        #GET STATUS PROVISIONER LOGS
         IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
         for pod in "${pods[@]}"; do
           if [[ $pod == *"provisioner"* ]]; then
@@ -61,7 +80,7 @@ runs:
 
     - name: Check pods status
       run: |
-        echo Check pods status
+        #CHECK PODS STATUS
         IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
         for pod in "${pods[@]}"; do
           if [[ $pod != *"provisioner"* ]]; then
@@ -80,14 +99,13 @@ runs:
 
     - name: Get events from namespace
       run: | 
-        echo Get events from namespace
         file_name=artifacts/${{inputs.namespace}}_events.txt
-        kubectl events -n ${{inputs.namespace}} > file_name
+        kubectl events -n ${{inputs.namespace}} > $file_name
       shell: bash
 
     - name: Get yaml from pods
       run: |
-        echo Get yaml from pods
+        #GET YAML FROM PODS
         file_name=artifacts/${{inputs.namespace}}_pod_yamls.txt
         IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
         echo "Yaml files from pods: " > $file_name
@@ -95,32 +113,67 @@ runs:
             echo $pod >> $file_name
             kubectl get pod "$pod" -n ${{inputs.namespace}} -oyaml >> $file_name
         done
-        cat $file_name
       shell: bash
 
     - name: Get logs from all containers in pods
       run: |
-        echo Get logs from all containers in pods
+        #GET LOGS FROM ALL CONTAINERS IN PODS
         file_name=artifacts/${{inputs.namespace}}_log_from_containers.txt
         IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
         echo "Logs from all containers in pods: " > $file_name
         for pod in "${pods[@]}"; do
-            containers=$(kubectl get pods --namespace kube-system -o jsonpath="{.items[*].spec.containers[*].name}")
-            IFS=' ' read -ra containers_list <<< "$containers_str"
-            for container in "${containers_list[@]}"; do
-              echo $container >> $file_name
+            IFS=' ' read -ra containers <<< $(kubectl get pod "$pod" -n ${{inputs.namespace}} -o jsonpath="{.spec.containers[*].name}")
+            for container in "${containers[@]}"; do
+              echo $pod $container >> $file_name
               kubectl logs "$pod" -n ${{inputs.namespace}} -c "$container" >> $file_name
             done
         done
       shell: bash
 
+    - name: Get current time
+      run: |
+        #GET CURRENT TIME
+        CURRENT_TIME=$(date -u +'%Y%m%d%H%M%S')
+        echo "CURRENT_TIME=$CURRENT_TIME" >> $GITHUB_ENV
+      shell: bash
+
     - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
-        name: ${{github.job}}_${{inputs.namespace}}_artifacts
+        name: ${{github.job}}_${{inputs.namespace}}_artifacts_${{env.CURRENT_TIME}}
         path: artifacts/
 
-    - name: Get pods
+    - name: Get logs from test pod
       run: |
-        kubectl get pods -n ${{inputs.namespace}}
+        #GET LOGS FROM TEST POD
+        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
+        for pod in "${pods[@]}"; do
+          if [[ $pod == *"tests"* ]]; then
+            test_pod=$pod
+          fi
+        done
+        if [[ $test_pod ]]; then
+          echo "test_pod=$test_pod"
+          for i in {1..${{inputs.max_attempts}}}; do
+            status=$(kubectl get pod $test_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
+            if [[ "$status" == 'Running' ]]; then
+              break
+            fi
+            sleep ${{inputs.timeout}}
+          done
+          for i in {1..${{inputs.max_attempts}}}; do
+            logs=$(kubectl logs $test_pod -n ${{inputs.namespace}})
+            if [[ $logs == *"Report: /opt/robot/output/report.html"* ]]; then
+              break
+            fi
+            sleep ${{inputs.timeout}}
+          done
+          echo 'TEST LOGS: '
+          kubectl logs $test_pod -n ${{inputs.namespace}}
+          if [[ $logs == *"| FAIL |"* ]]; then
+            exit 1
+          fi
+        else
+          echo There is no test pod
+        fi
       shell: bash
