Restricted install (#2)

diff --git a/actions/check_status_provisioner/action.yml b/actions/check_status_provisioner/action.yml
--- a/actions/check_status_provisioner/action.yml
+++ b/actions/check_status_provisioner/action.yml
@@ -1,47 +1,118 @@
 name: 'Custom GitHub Action'
 description: 'A GitHub Action that takes an input and returns the square of the number'
-#inputs:
-#  namespace:
-#    description: 'namespace where service is installed'
-#    required: true
 
 runs:
   using: 'composite'
   steps:
-    - name: Get pods
-      run: 'kubectl get pods -n ${{env.namespace}}'
+    - name: Create folder for artifacts
+      run: mkdir -p artifacts
       shell: bash
-    - name: Get logs
+
+#    - name: Sleep
+#      run: sleep 30s
+#      shell: bash
+
+    - name: Get pods
+      run: kubectl get pods -n ${{env.namespace}}
+      shell: bash
+
+    - name: Get status provisioner logs
       run: |
-        pods=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{env.namespace}}  | tr -s '\r\n' ' ')
-        IFS=$' ' read -a pods_list <<< "$pods"
-        echo "$pods"
-        for pod in "${pods_list[@]}"; do
+        echo Get status provisioner logs
+        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{env.namespace}} | tr $'\n' ' ')
+        for pod in "${pods[@]}"; do
           if [[ $pod == *"provisioner"* ]]; then
             provisioner_pod=$pod
           fi
         done
-        echo "provisioner_pod=$provisioner_pod"
-        for i in {1..${{env.max_attempts}}}; do
-          status=$(kubectl get pod $provisioner_pod -n ${{env.namespace}} -o jsonpath="{.status.phase}")
-          echo "status=$status"
-          if [[ "$status" == 'Succeeded' ]]; then
-            break
+        if [[ $provisioner_pod ]]; then
+          echo "provisioner_pod=$provisioner_pod"
+          for i in {1..${{env.max_attempts}}}; do
+            status=$(kubectl get pod $provisioner_pod -n ${{env.namespace}} -o jsonpath="{.status.phase}")
+            if [[ "$status" == 'Succeeded' ]]; then
+              break
+            fi
+            sleep ${{env.timeout}}
+          done
+          if [[ "$status" != 'Succeeded' ]]; then
+            echo $provisioner_pod pod has not Succeeded status
           fi
-          sleep ${{env.timeout}}
+          echo PROVISIONER LOGS:
+          kubectl logs $provisioner_pod -n ${{env.namespace}}
+          logs=$(kubectl logs $provisioner_pod -n ${{env.namespace}})
+          if [[ $logs != *"Failed components statuses are []"* ]]; then
+            echo Not all components are in succeed status after ${{env.max_attempts}} attempts
+            echo PODS:
+            kubectl get pods -n ${{env.namespace}}
+            exit 1
+          fi
+        else
+          echo provisioner pod is not found
+        fi
+      shell: bash
+
+    - name: Check pods status
+      run: |
+        echo Check pods status
+        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{env.namespace}} | tr $'\n' ' ')
+        for pod in "${pods[@]}"; do
+          if [[ $pod != *"provisioner"* ]]; then
+            for i in {1..${{env.max_attempts}}}; do
+              status=$(kubectl get pod $pod -n ${{env.namespace}} -o jsonpath="{.status.phase}")
+              if [[ "$status" == 'Running' ]]; then
+                break
+              fi
+              echo $pod is not in Running status
+              sleep ${{env.timeout}}
+            done
+          fi
         done
-        if [[ "$status" != 'Succeeded' ]]; then
-          echo $provisioner_pod pod has not Succeeded status 
-        fi
-        echo PROVISIONER LOGS:
-        kubectl logs $provisioner_pod -n ${{env.namespace}}
-        logs=$(kubectl logs $provisioner_pod -n ${{env.namespace}})
-        if [[ $logs != *"Failed components statuses are []"* ]]; then
-          echo Not all components are in succeed status after ${{env.max_attempts}} attempts
-          echo PODS:
-          kubectl get pods -n ${{env.namespace}}
-          echo EVENTS:
-          kubectl events -n ${{env.namespace}}
-          exit 1
-        fi
+        echo All pods are in Running status
+      shell: bash
+
+    - name: Get events from namespace
+      run: | 
+        echo Get events from namespace
+        file_name=artifacts/${{env.namespace}}_events.txt
+        kubectl events -n ${{env.namespace}} > file_name
+      shell: bash
+
+    - name: Get yaml from pods
+      run: |
+        echo Get yaml from pods
+        file_name=artifacts/${{env.namespace}}_pod_yamls.txt
+        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{env.namespace}} | tr $'\n' ' ')
+        echo "Yaml files from pods: " > $file_name
+        for pod in "${pods[@]}"; do
+            echo $pod >> $file_name
+            kubectl get pod "$pod" -n ${{env.namespace}} -oyaml >> $file_name
+        done
+        cat $file_name
+      shell: bash
+
+    - name: Get logs from all containers in pods
+      run: |
+        echo Get logs from all containers in pods
+        file_name=artifacts/${{env.namespace}}_log_from_containers.txt
+        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{env.namespace}} | tr $'\n' ' ')
+        echo "Logs from all containers in pods: " > $file_name
+        for pod in "${pods[@]}"; do
+            containers=$(kubectl get pods --namespace kube-system -o jsonpath="{.items[*].spec.containers[*].name}")
+            IFS=' ' read -ra containers_list <<< "$containers_str"
+            for container in "${containers_list[@]}"; do
+              echo $container >> $file_name
+              kubectl logs "$pod" -n ${{env.namespace}} -c "$container" >> $file_name
+            done
+        done
+      shell: bash
+
+    - name: Upload artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: ${{github.job}}_${{env.namespace}}_artifacts
+        path: artifacts/
+
+    - name: Get pods
+      run: |
+        kubectl get pods -n ${{env.namespace}}
       shell: bash
