feat: fix replacement

diff --git a/actions/shared/helm_deploy/action.yml b/actions/shared/helm_deploy/action.yml
--- a/actions/shared/helm_deploy/action.yml
+++ b/actions/shared/helm_deploy/action.yml
@@ -171,17 +171,11 @@ runs:
       if: inputs.image_replacement != ''
       shell: bash
       run: |
-        template_name=$(basename "${{inputs.path_to_template}}")
-        target_file="${{inputs.repository_name}}/${{inputs.path_to_chart}}/$template_name"
-        echo "Searching for patroni image in $target_file"
-        if grep -q "dockerImage:.*pgskipper-patroni" "$target_file"; then
-          echo "Found patroni image. Replacing with: ${{ inputs.image_replacement }}"
-          sed -i "s|\(dockerImage: .*/\)[^:]*\(:\)|\1${{ inputs.image_replacement }}\2|g" "$target_file"
-          echo "New line content:"
-          grep "dockerImage" "$target_file"
-        else
-          echo "::warning::Line 'dockerImage' with patroni pattern not found in $target_file. Skipping replacement."
-        fi
+        FILE_NAME=$(basename "${{inputs.path_to_template}}")
+        cd "${{inputs.repository_name}}/${{inputs.path_to_chart}}"  
+        echo "Updating patroni.dockerImage in $FILE_NAME to: ${{ inputs.image_replacement }}"
+        sed -i "s|\(dockerImage: .*/\)[^:]*\(:\)|\1${{ inputs.image_replacement }}\2|g" "$FILE_NAME"
+        grep "dockerImage" "$FILE_NAME" || echo "Warning: dockerImage not found"
   
     - name: Update versions in values
       id: update-versions
