feat: fix after review

diff --git a/actions/shared/helm_deploy/action.yml b/actions/shared/helm_deploy/action.yml
--- a/actions/shared/helm_deploy/action.yml
+++ b/actions/shared/helm_deploy/action.yml
@@ -94,13 +94,19 @@ runs:
       # language=bash
       run: |
         # ▶️ Replace CRDs
-        cd ${{inputs.repository_name}}/${{inputs.path_to_chart}}
+        cd "${{inputs.repository_name}}/${{inputs.path_to_chart}}"
         if [ -d "./crds" ]; then
           echo "CRDs directory exists"
           for file in ./crds/*; do
             if [ -f "$file" ]; then
               echo "Processing file: $file"
               CRD_NAME=$(yq e '.metadata.name' "$file" 2>/dev/null)
+
+              if [ -z "$CRD_NAME" ]; then
+                echo "::error::Could not extract CRD name from $file"
+                exit 1
+              fi
+
               echo "Found CRD: $CRD_NAME"
               if kubectl get crd "$CRD_NAME" > /dev/null 2>&1; then
                   echo "CRD $CRD_NAME already exists. Updating..."
@@ -112,7 +118,7 @@ runs:
             fi
           done
         else
-          echo "Directory with CRDs not found!"
+          echo "::error::Directory with CRDs not found!"
           exit 1
         fi
 
diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -100,13 +100,17 @@ runs:
             echo "ERROR_FLAG=true" >> $GITHUB_ENV
           fi
           if [[ $logs != *"Failed components statuses are []"* ]]; then
-            echo "::error:: Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
+            echo "::error::Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts"
             echo PODS:
             kubectl get pods -n ${{inputs.namespace}}
             echo "ERROR_FLAG=true" >> $GITHUB_ENV
           fi
         else
           echo "Status provisioner pod is not found. Checking CR..."
+          if [ -z "${{inputs.cr_kind}}" ] || [ -z "${{inputs.cr_name}}" ]; then
+              echo "::error::Missing parameters for CR check"
+              exit 1
+          fi
           for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
             cr_yaml=$(kubectl get "${{inputs.cr_kind}}" "${{inputs.cr_name}}" -n "${{inputs.namespace}}" -o yaml)
             IFS='|' read -ra messages <<< "${{ inputs.ADDITIONAL_SUCCESS_MESSAGES }}"
