feat: replace tags in values

diff --git a/actions/shared/helm_deploy/action.yml b/actions/shared/helm_deploy/action.yml
--- a/actions/shared/helm_deploy/action.yml
+++ b/actions/shared/helm_deploy/action.yml
@@ -62,9 +62,9 @@ inputs:
     type: string
     default: ''
 
-  test_tag:
+  test_tags:
     description: |
-      Test tag
+      Test tags
     required: true
     default: ''
 
@@ -206,6 +206,31 @@ runs:
           fi
         fi
 
+    - name: Update Test Tags
+      if: inputs.test_tags != ''
+      shell: bash
+      run: |
+        # ▶️ Replace test tags
+        path_to_file="${{inputs.path_to_template}}"
+        new_tags="${{ inputs.test_tags }}"
+        current_tags=$(grep -E '^[[:space:]]*tags:[[:space:]]*' "$file" | head -n1 | sed -E 's/^[[:space:]]*tags:[[:space:]]*//; s/^"//; s/"$//')
+        if [ -z "$current_tags" ]; then
+          echo "::warning::No 'tags' field found in $file"
+          continue
+        fi
+        if [ "$current_tags" = "$new_tags" ]; then
+          echo "ℹ️ $file: tags already set to '$current'. No changes needed."
+        else
+          echo "🔄 $file: replacing '$current_tags' tags -> '$new_tags' tags"
+          sed -i -E 's/^([[:space:]]*tags:[[:space:]]*).*/\1'"$new_tags"'/' "$file"
+          if grep -qE '^[[:space:]]*tags:[[:space:]]*'"$new_tags" "$file"; then
+            echo "✅ $file: successfully updated"
+          else
+            echo "::error::Failed to update $file"
+            exit 1
+          fi
+        fi
+
     - name: Update versions in values
       id: update-versions
       if: ${{ steps.check-release.outputs.is_release == 'false' }}
@@ -227,25 +252,11 @@ runs:
         template_name=$(basename "${{inputs.path_to_template}}")
         echo $template_name
         cd ${{inputs.repository_name}}/${{inputs.path_to_chart}}
-        helm_args=(
-          "${{ inputs.deploy_mode }}"
-          "${{ inputs.service_name }}"
-          "."
-          "-f" "$template_name"
-          "-n" "${{ inputs.namespace }}"
-          "--timeout" "10m"
-        )
-
-        if [[ -n "${{ inputs.test_tag }}" ]]; then
-          echo "tags=${{ inputs.test_tag }}"
-          helm_args+=(--set "integrationTests.tags=${{ inputs.test_tag }}")
+        if [[ "${{inputs.restricted}}" == "false" ]]; then
+          helm ${{inputs.deploy_mode}} ${{inputs.service_name}} . -f $template_name -n ${{inputs.namespace}} --timeout 10m
+        else
+          helm ${{inputs.deploy_mode}} ${{inputs.service_name}} . -f $template_name -n ${{inputs.namespace}} --timeout 10m --skip-crds
         fi
-
-        if [[ "${{ inputs.restricted }}" != "false" ]]; then
-          helm_args+=(--skip-crds)
-        fi
-
-        helm "${helm_args[@]}"
 
     - name: Get docker images
       shell: bash
