feat: cassandra update templates

diff --git a/actions/shared/helm_deploy/action.yml b/actions/shared/helm_deploy/action.yml
--- a/actions/shared/helm_deploy/action.yml
+++ b/actions/shared/helm_deploy/action.yml
@@ -135,7 +135,8 @@ runs:
             fi
           done
         else
-          echo "::warning::Directory with CRDs not found!"
+          echo "::error::Directory with CRDs not found!"
+          exit 1
         fi
 
     - name: Create restricted resources
