feat: add nightly pipeline for rabbit

diff --git a/.github/workflows/rabbitmq.yaml b/.github/workflows/rabbitmq.yaml
--- a/.github/workflows/rabbitmq.yaml
+++ b/.github/workflows/rabbitmq.yaml
@@ -23,6 +23,11 @@ on:
         type: string
         required: false
         default: ubuntu-latest
+      scope:
+        description: RabbitMQ Test Scope (pr or nightly)
+        type: string
+        required: false
+        default: pr
   workflow_call:
     inputs:
       repository_name:
@@ -42,6 +47,11 @@ on:
         type: string
         required: false
         default: ubuntu-latest
+      scope:
+        description: RabbitMQ Test Scope (pr or nightly)
+        type: string
+        required: false
+        default: pr
     secrets:
       AWS_S3_ACCESS_KEY_ID:
         required: true
@@ -83,7 +93,15 @@ jobs:
         working-directory: ${{ github.workspace }}/qubership-test-pipelines
         run: |
           chmod +x ./scripts/matrix.sh
-          ./scripts/matrix.sh "${{ steps.get-latest-tag.outputs.latest_tag }}" ./workflow-config/rabbitmq.yaml "${{ inputs.service_branch }}"
+          if [[ "${{ inputs.scope }}" == "nightly" ]]; then
+            CONFIG_FILE="./workflow-config/rabbitmq_nightly.yaml"
+          elif [[ "${{ inputs.scope }}" == "pr" ]]; then
+            CONFIG_FILE="./workflow-config/rabbitmq.yaml"
+          else
+            echo "::error::Invalid scope parameter '${{ inputs.scope }}'. Must be 'pr' or 'nightly'."
+            exit 1
+          fi
+          ./scripts/matrix.sh "${{ steps.get-latest-tag.outputs.latest_tag }}" "$CONFIG_FILE" "${{ inputs.service_branch }}"
 
   RabbitMQ-Test-Cases:
     runs-on: ${{inputs.runner_type}}
@@ -93,9 +111,9 @@ jobs:
       matrix:
         test: ${{ fromJson(needs.prepare.outputs.matrix) }}
     env:
-      test_completion_max_retries: 30
+      test_completion_max_retries: 20
       test_completion_retry_interval: 10s
-      service_ready_max_retries: 60
+      service_ready_max_retries: 200
       service_ready_retry_interval: 10s
     name: ${{ matrix.test.name }}
     steps:
@@ -113,9 +131,43 @@ jobs:
           path: qubership-test-pipelines
       - name: Create cluster
         uses: ./qubership-test-pipelines/actions/shared/create_cluster
-      # - name: Install Monitoring
-        # uses: ./qubership-test-pipelines/actions/monitoring/helm_deploy_monitoring
       # == End Common steps ==
+
+      # == Start Monitoring installation =======
+      - name: Install Monitoring
+        if: matrix.test.monitoring == true
+        uses: ./qubership-test-pipelines/actions/shared/helm_deploy
+        with:
+          path_to_template: templates/monitoring/vm_without_tests.yml
+          service_branch: main
+          service_name: monitoring
+          repository_name: Netcracker/qubership-monitoring-operator
+          path_to_chart: charts/qubership-monitoring-operator
+          namespace: monitoring
+          restricted: false
+
+      - name: Get Installed Monitoring CR name
+        if: matrix.test.monitoring == true
+        uses: ./qubership-test-pipelines/actions/shared/get_crds
+        id: install_monitoring_get_crds
+        with:
+          crd_location: Netcracker/qubership-monitoring-operator/charts/qubership-monitoring-operator/crds
+
+      - name: Verify Monitoring installation
+        if: matrix.test.monitoring == true
+        uses: ./qubership-test-pipelines/actions/shared/verify_installation
+        with:
+          namespace: monitoring
+          test_completion_max_retries: 40
+          test_completion_retry_interval: 10s
+          service_ready_max_retries: 80
+          service_ready_retry_interval: 10s
+          artifact_name: Install_Monitoring_${{ matrix.test.artifact_name }}
+          monitoring_pipeline: true
+          crd_list: ${{ steps.install_monitoring_get_crds.outputs.crd_names }}
+          check_tests: true
+          repository_name: Netcracker/qubership-monitoring-operator
+      # == End Monitoring installation =======
 
       # == Start Install steps ==
       # TLS setup
